// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "check-material-format-compliance" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    prepared_materials: z.json().describe("用户准备的材料清单，每项包含文档名称、文件格式、页数、语言和命名方式").optional(),
    target_opportunity: z.json().describe("目标岗位描述中的格式、篇幅、命名和语言要求").optional(),
    material_requirements: z.json().describe("可选：已梳理出的岗位材料要求清单，存在时优先作为格式核对基准").optional(),
    submission_context: z.json().describe("可选：投递平台和提交方式，用于补充额外的格式规则；未提供时按通用格式规则检查").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const CheckMaterialFormatComplianceTool = buildTool({
  name: "CheckMaterialFormatCompliance",
  searchHint: "check whether prepared application materials comply with the job posting format requirements",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "检查材料格式是否合规"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 检查材料格式是否合规"
  },
  renderToolUseRejectedMessage() {
    return "检查材料格式是否合规 rejected"
  },
  renderToolUseErrorMessage() {
    return "检查材料格式是否合规 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 检查材料格式是否合规"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
