// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "tailor-resume-for-opportunity" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    resume_draft: z.string().trim().min(1).describe("用户提供的现有简历草稿文本，可包含工作经历、项目、技能和教育信息").optional(),
    target_opportunity: z.json().describe("目标岗位的描述，包括职责、要求关键词、投递说明和招聘方关注点").optional(),
    application_focus_brief: z.json().describe("上一阶段形成的投递材料准备要点").optional(),
    user_profile: z.json().describe("已确认的用户画像，用于校验简历内容是否在事实范围内").optional(),
    format_preferences: z.json().describe("用户对简历语言、篇幅、版式和命名规则的要求").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const TailorResumeForOpportunityTool = buildTool({
  name: "TailorResumeForOpportunity",
  searchHint: "按岗位要求调整简历重点并保留事实边界",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "按岗位要求调整简历重点"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return false
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 按岗位要求调整简历重点"
  },
  renderToolUseRejectedMessage() {
    return "按岗位要求调整简历重点 rejected"
  },
  renderToolUseErrorMessage() {
    return "按岗位要求调整简历重点 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 按岗位要求调整简历重点"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
