// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "followup-prioritization" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    application_tracking_ledger: z.json().describe("用户的追踪记录，由用户直接提供当前版本，包含各机会的状态和下一步动作").optional(),
    opportunity_pursuit_ranking: z.json().describe("用户已确认的机会投递优先顺序，用于计算跟进价值").optional(),
    user_followup_preferences: z.json().describe("用户偏好的联系渠道、时间段、频率和不想反复打扰的对象").optional(),
    user_available_time: z.json().describe("用户可投入跟进的时间窗口或总体时间上限，具体数值由用户提供").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const FollowupPrioritizationTool = buildTool({
  name: "FollowupPrioritization",
  searchHint: "digest application responses and prioritize who to follow up with and what to do next",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "帮我整理投递情况，告诉下一步该跟进谁"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 帮我整理投递情况，告诉下一步该跟进谁"
  },
  renderToolUseRejectedMessage() {
    return "帮我整理投递情况，告诉下一步该跟进谁 rejected"
  },
  renderToolUseErrorMessage() {
    return "帮我整理投递情况，告诉下一步该跟进谁 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 帮我整理投递情况，告诉下一步该跟进谁"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
