// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "extract-application-requirements" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    job_posting_text: z.string().trim().min(1).describe("用户提供的岗位描述或材料要求文本，与已验证岗位清单中内容等价时可省略").optional(),
    job_posting_url: z.string().trim().min(1).describe("可选：用户提供的岗位页面链接，用于抓取岗位描述").optional(),
    job_posting_content: z.string().trim().min(1).describe("通过 WebFetch 从岗位链接抓取到的页面正文；仅在用户提供链接时生成").optional(),
    verified_opportunity_list: z.json().describe("已验证的真实岗位机会清单，用于核对岗位标识和已有要求").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const ExtractApplicationRequirementsTool = buildTool({
  name: "ExtractApplicationRequirements",
  searchHint: "extract required application materials, formats, length limits, language, and deadlines from a job posting or verified opportunity",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "梳理岗位要求交什么材料"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 梳理岗位要求交什么材料"
  },
  renderToolUseRejectedMessage() {
    return "梳理岗位要求交什么材料 rejected"
  },
  renderToolUseErrorMessage() {
    return "梳理岗位要求交什么材料 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 梳理岗位要求交什么材料"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
