import {describe,expect,test}from'bun:test'
import{mkdtemp}from'node:fs/promises';import{join}from'node:path';import{tmpdir}from'node:os'
import type{ToolUseContext}from'../src/Tool.js';import{publishActionArtifact}from'../src/artifacts/actionArtifactPublisher.js'
import{ActivateLearningPlanTool}from'../src/tools/ActivateLearningPlanTool/ActivateLearningPlanTool.js';import{UpdateLearningProgressTool}from'../src/tools/UpdateLearningProgressTool/UpdateLearningProgressTool.js';import{learningStateService}from'../src/learning/learningStateService.js'
import{LearningProgressAssessmentTool}from'../src/tools/LearningProgressAssessmentTool/LearningProgressAssessmentTool.js'
const ctx=(workspaceDir:string)=>({actionArtifactRuntime:{workspaceDir,sessionId:'s',userId:'u1'}}as unknown as ToolUseContext)
const allow=async()=>({behavior:'allow' as const,updatedInput:{}})
async function artifact(workspaceDir:string,type:string,payload:Record<string,unknown>){return(await publishActionArtifact({workspaceDir,sessionId:'s',userId:'u1',completion:{skill_call_id:`c-${type}`,skill_name:'test',agent_id:'a',outcome:'success',summary:'x',completed_at:'2026-08-20T10:00:00.000Z',result:{}},adapter:{artifactType:type,artifactSlug:type.toLowerCase(),schemaVersion:'1.0',toCanonical:()=>({schema_version:'1.0',artifact_type:type,created_at:'2026-08-20T10:00:00.000Z',lineage:{skill_call_id:'c',skill_name:'test',agent_id:'a'},...payload}),render:()=>({title:type,summary:type,renderMode:'html',html:'<p>x</p>'})}}))!}
async function setup(){const w=await mkdtemp(join(tmpdir(),'progress-'));const p=await artifact(w,'LearningPlan',{plan:{version:1,updated_at:'2026-08-20T10:00:00.000Z',planning_constraints:{available_time_per_week:'8h',deadline:null},stages:[{id:'s1'},{id:'s2'}]}});const active=await ActivateLearningPlanTool.call({plan_ref:p.artifact_ref},ctx(w),allow);const planId=active.data.plan_id;const pkg=await artifact(w,'LearningStagePackage',{package:{plan_id:planId,plan_ref:p.artifact_ref,stage_id:'s1'}});return{w,p,planId,pkg}}
describe('UpdateLearningProgress',()=>{
 test('requires ready_for_assessment before running the assessment Action',async()=>{const{w,planId,pkg}=await setup();await UpdateLearningProgressTool.call({plan_id:planId,operation:'start_stage',stage_package_ref:pkg.artifact_ref},ctx(w),allow);await expect(LearningProgressAssessmentTool.call({plan_id:planId,evidence:[{source_type:'conversation',summary:'submitted work'}]},ctx(w),allow)).rejects.toThrow('STAGE_NOT_READY_FOR_ASSESSMENT')})
 test('starts, marks ready, continues, and preserves version on duplicates',async()=>{const{w,planId,pkg,p}=await setup();let r=await UpdateLearningProgressTool.call({plan_id:planId,operation:'start_stage',stage_package_ref:pkg.artifact_ref},ctx(w),allow);expect(r.data.current_stage_status).toBe('in_progress');const v1=(await learningStateService.getUserState(w)).version;r=await UpdateLearningProgressTool.call({plan_id:planId,operation:'start_stage',stage_package_ref:pkg.artifact_ref},ctx(w),allow);expect(r.data.operation_status).toBe('already_applied');expect((await learningStateService.getUserState(w)).version).toBe(v1);await UpdateLearningProgressTool.call({plan_id:planId,operation:'mark_ready_for_assessment'},ctx(w),allow);const assessment=await artifact(w,'LearningProgressAssessment',{assessment:{plan_id:planId,plan_ref:p.artifact_ref,stage_id:'s1',readiness:'continue'}});r=await UpdateLearningProgressTool.call({plan_id:planId,operation:'apply_assessment',assessment_ref:assessment.artifact_ref,decision:'continue'},ctx(w),allow);expect(r.data.current_stage_status).toBe('in_progress')})
 test('advances and completes the final stage only with advance readiness',async()=>{const{w,planId,pkg,p}=await setup();await UpdateLearningProgressTool.call({plan_id:planId,operation:'start_stage',stage_package_ref:pkg.artifact_ref},ctx(w),allow);await UpdateLearningProgressTool.call({plan_id:planId,operation:'mark_ready_for_assessment'},ctx(w),allow);const a1=await artifact(w,'LearningProgressAssessment',{assessment:{plan_id:planId,plan_ref:p.artifact_ref,stage_id:'s1',readiness:'advance'}});let r=await UpdateLearningProgressTool.call({plan_id:planId,operation:'apply_assessment',assessment_ref:a1.artifact_ref,decision:'advance'},ctx(w),allow);expect(r.data.current_stage_id).toBe('s2');expect(r.data.completed_stage_ids).toEqual(['s1']);const pkg2=await artifact(w,'LearningStagePackage',{package:{plan_id:planId,plan_ref:p.artifact_ref,stage_id:'s2'}});await UpdateLearningProgressTool.call({plan_id:planId,operation:'start_stage',stage_package_ref:pkg2.artifact_ref},ctx(w),allow);await UpdateLearningProgressTool.call({plan_id:planId,operation:'mark_ready_for_assessment'},ctx(w),allow);const a2=await artifact(w,'LearningProgressAssessment',{assessment:{plan_id:planId,plan_ref:p.artifact_ref,stage_id:'s2',readiness:'advance'}});r=await UpdateLearningProgressTool.call({plan_id:planId,operation:'apply_assessment',assessment_ref:a2.artifact_ref,decision:'advance'},ctx(w),allow);expect(r.data.plan_status).toBe('completed');expect(r.data.completed_stage_ids).toEqual(['s1','s2'])})
 test('rejects a mismatched package and unsupported advance',async()=>{const{w,planId,p}=await setup();const wrong=await artifact(w,'LearningStagePackage',{package:{plan_id:planId,plan_ref:p.artifact_ref,stage_id:'s2'}});await expect(UpdateLearningProgressTool.call({plan_id:planId,operation:'start_stage',stage_package_ref:wrong.artifact_ref},ctx(w),allow)).rejects.toThrow('STAGE_PACKAGE_MISMATCH')})
})
