// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
export const generatedSkillActionToolNames = new Set([
  "baselineassessment",
  "careercompetencymodel",
  "learningplan",
  "learningprogressassessment",
  "learningstagedesign",
])
