// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
/* eslint-disable @typescript-eslint/no-require-imports */
export function getGeneratedSkillActionTools() {
  return [
    (require("./BaselineAssessmentTool/BaselineAssessmentTool.js") as typeof import("./BaselineAssessmentTool/BaselineAssessmentTool.js")).BaselineAssessmentTool,
    (require("./CareerCompetencyModelTool/CareerCompetencyModelTool.js") as typeof import("./CareerCompetencyModelTool/CareerCompetencyModelTool.js")).CareerCompetencyModelTool,
    (require("./LearningPlanTool/LearningPlanTool.js") as typeof import("./LearningPlanTool/LearningPlanTool.js")).LearningPlanTool,
  ] as const
}
/* eslint-enable @typescript-eslint/no-require-imports */
