// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
export const generatedSkillActionToolNames = new Set([
  "webappdev",
  "baselineassessment",
  "careercompetencymodel",
  "developwebgame",
  "webappinformationcollection",
  "learningplan",
  "learningprogressassessment",
  "learningstagedesign",
])
