// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "understand-entry-requirements" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    target_direction: z.string().trim().min(1).describe("要了解进入要求的目标方向或岗位类型").optional(),
    target_region: z.string().trim().min(1).describe("用户关心的目标地区，用于限定地区差异").optional(),
    target_level: z.string().trim().min(1).describe("用户关心的职级或经验阶段，如入门、初级、中级；为空则覆盖主要阶段").optional(),
    entry_search_results: z.json().describe("公开来源中关于该方向任职要求、招聘门槛和成长路径的检索结果").optional(),
    entry_page_extracts: z.json().describe("筛选后的原文页面内容，用于核对具体任职条件和路径").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const EntryRequirementsReportTool = buildTool({
  name: "EntryRequirementsReport",
  searchHint: "understand entry requirements, qualification gates, progression paths, and regional differences for a specific career direction",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "了解目标方向的进入要求和成长路径"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return false
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 了解目标方向的进入要求和成长路径"
  },
  renderToolUseRejectedMessage() {
    return "了解目标方向的进入要求和成长路径 rejected"
  },
  renderToolUseErrorMessage() {
    return "了解目标方向的进入要求和成长路径 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 了解目标方向的进入要求和成长路径"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
