// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "draft-contact-message" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    contact_context: z.json().describe("对方称呼、关系类型、真实共同点或交集、公开联系方式以及拟使用的场合说明").optional(),
    verified_opportunity_list: z.json().describe("用户已经确认的真实机会清单，用于在消息中准确说明申请目标").optional(),
    tailored_application_packages: z.json().describe("用户已准备好的投递材料，用于在消息中引用真实材料而不是虚构经历").optional(),
    user_profile: z.json().describe("用户已有的画像信息，用于保证消息中对自身的描述真实一致").optional(),
    message_preferences: z.json().describe("用户对语气、长度、渠道语言风格、称谓以及希望避免的措辞的偏好").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const DraftContactMessageTool = buildTool({
  name: "DraftContactMessage",
  searchHint: "draft a restrained contact message for networking, informational interviews, referrals, or application requirement clarification",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "帮我写一段自然、克制的联系消息"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return false
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 帮我写一段自然、克制的联系消息"
  },
  renderToolUseRejectedMessage() {
    return "帮我写一段自然、克制的联系消息 rejected"
  },
  renderToolUseErrorMessage() {
    return "帮我写一段自然、克制的联系消息 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 帮我写一段自然、克制的联系消息"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
