// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "application-tracking-status-recorder" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    status_update_events: z.json().describe("用户口述或粘贴的投递、回复、面试、跟进、关闭事件，时间和来源由用户提供").optional(),
    current_tracking_records: z.json().describe("用户已有的追踪记录，可为空，用于增量更新而不是覆盖").optional(),
    verified_opportunity_list: z.json().describe("用户已经确认的真实机会清单，用于关联每一条状态记录到正确机会").optional(),
    user_followup_cadence: z.json().describe("用户希望多久跟进一次、用什么方式跟进，具体节奏由用户提供").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const ApplicationTrackingStatusRecorderTool = buildTool({
  name: "ApplicationTrackingStatusRecorder",
  searchHint: "记录并更新投递、回复、面试、跟进和关闭状态为结构化台账",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "帮我记录投递、回复和跟进状态"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 帮我记录投递、回复和跟进状态"
  },
  renderToolUseRejectedMessage() {
    return "帮我记录投递、回复和跟进状态 rejected"
  },
  renderToolUseErrorMessage() {
    return "帮我记录投递、回复和跟进状态 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 帮我记录投递、回复和跟进状态"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
