// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "understand-real-work" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    target_direction: z.string().trim().min(1).describe("用户要了解工作内容的具体方向或岗位类型").optional(),
    work_context: z.json().describe("用户指定的行业、组织类型或地区等背景，用于限定工作内容描述").optional(),
    real_work_search_results: z.json().describe("公开来源中关于该方向日常工作、项目和交付物的检索结果，用于提炼真实工作活动").optional(),
    real_work_page_extracts: z.json().describe("从检索结果中筛选出的原文页面内容，用于提炼真实工作活动").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const UnderstandRealWorkProfileTool = buildTool({
  name: "UnderstandRealWorkProfile",
  searchHint: "research role context, daily work, deliverables, collaborators, and team environment from public evidence",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "了解一个方向的实际日常工作"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 了解一个方向的实际日常工作"
  },
  renderToolUseRejectedMessage() {
    return "了解一个方向的实际日常工作 rejected"
  },
  renderToolUseErrorMessage() {
    return "了解一个方向的实际日常工作 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 了解一个方向的实际日常工作"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
