// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "outreach-lead-sequencing" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    referral_entry_lead_list: z.json().describe("用户已有产物，是按机会整理的公开入口、渠道和联系人线索清单").optional(),
    matched_network_lead_list: z.json().describe("用户已有产物，是从现有联系人中筛出的可接触内推线索清单").optional(),
    opportunity_pursuit_ranking: z.json().describe("场景已有产物，是用户已确认的机会投递优先顺序，用于决定先围绕哪个机会接触人").optional(),
    user_contact_rules: z.json().describe("用户对接触方式的限制、不想打扰的人、渠道排除项和频率上限").optional(),
    user_time_budget: z.json().describe("用户最近一段可投入的总时间和希望分批接触的节奏").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const OutreachLeadSequencingTool = buildTool({
  name: "OutreachLeadSequencing",
  searchHint: "sequence outreach and referral leads by opportunity priority and user contact constraints",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "排定联系先后顺序"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 排定联系先后顺序"
  },
  renderToolUseRejectedMessage() {
    return "排定联系先后顺序 rejected"
  },
  renderToolUseErrorMessage() {
    return "排定联系先后顺序 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 排定联系先后顺序"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
