// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "network-action-plan" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    current_situation_snapshot: z.json().describe("用户当前的进展、已投递清单、已有联系人、待核验线索等现状信息，由用户直接提供").optional(),
    opportunity_pursuit_ranking: z.json().describe("用户已确认的机会投递优先顺序，用于安排行动计划中的先后").optional(),
    user_time_and_rules: z.json().describe("用户可投入的周期、每周时间、联系方式上限、偏好渠道和不能打扰的时间").optional(),
    user_profile: z.json().describe("用户已有的画像信息，用于确保计划符合用户真实条件和偏好").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const NetworkActionPlanTool = buildTool({
  name: "NetworkActionPlan",
  searchHint: "制定接下来一段时间的人脉跟进和拓展行动计划",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "人脉跟进与拓展行动计划"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return false
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 人脉跟进与拓展行动计划"
  },
  renderToolUseRejectedMessage() {
    return "人脉跟进与拓展行动计划 rejected"
  },
  renderToolUseErrorMessage() {
    return "人脉跟进与拓展行动计划 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 人脉跟进与拓展行动计划"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
