// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "record-meeting-outcome" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    meeting_notes: z.json().describe("用户口述或粘贴的交流内容，例如对方提到的事、自己的回应、被问到的问题和口头承诺").optional(),
    application_tracking_ledger: z.json().describe("用户已有产物，是与该沟通相关机会的当前追踪状态，用于把新记录接进去").optional(),
    verified_opportunity_list: z.json().describe("场景已有产物，是用户确认过的真实机会清单，用于把本次沟通绑定到对应机会").optional(),
    followup_rules: z.json().describe("用户对自己要履行的承诺、跟进方式和不希望再接触的对象的说明").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const RecordMeetingOutcomeTool = buildTool({
  name: "RecordMeetingOutcome",
  searchHint: "record meeting communication outcomes, commitments, and follow-up items",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "记录沟通结果与待办"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 记录沟通结果与待办"
  },
  renderToolUseRejectedMessage() {
    return "记录沟通结果与待办 rejected"
  },
  renderToolUseErrorMessage() {
    return "记录沟通结果与待办 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 记录沟通结果与待办"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
