// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "review-outreach-drafts" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    contact_message_drafts: z.json().describe("用户已有产物，是针对不同联系场景生成的待发送消息草稿").optional(),
    user_contact_rules: z.json().describe("用户对隐私、可透露信息、称呼方式和不想越过的界限的说明").optional(),
    message_preferences: z.json().describe("用户偏好的语气、长度、用词习惯和希望避免的表达").optional(),
    network_lead_verification_report: z.json().describe("用户已有产物，是待联系对象与渠道的事实核实结果，用于检查消息里有没有与事实不符的说法").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const ReviewOutreachDraftsTool = buildTool({
  name: "ReviewOutreachDrafts",
  searchHint: "review contact message drafts for risk flags and suggested revisions before sending",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "帮我把要发出去的消息再过一遍，标出不合适的地方"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 帮我把要发出去的消息再过一遍，标出不合适的地方"
  },
  renderToolUseRejectedMessage() {
    return "帮我把要发出去的消息再过一遍，标出不合适的地方 rejected"
  },
  renderToolUseErrorMessage() {
    return "帮我把要发出去的消息再过一遍，标出不合适的地方 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 帮我把要发出去的消息再过一遍，标出不合适的地方"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
