// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "compare-profile-with-requirements" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    user_profile: z.json().describe("用户画像中的已有事实、证据和偏好，作为对照的个人侧输入").optional(),
    target_direction: z.string().trim().min(1).describe("要对照的目标方向或岗位类型").optional(),
    requirements_input: z.json().describe("用户提供的任职要求文本或要求清单；用户未提供时可留空").optional(),
    requirement_search_results: z.json().describe("当用户未提供要求清单时，检索到的该方向典型任职要求，用于补充对照依据").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const CompareProfileWithRequirementsTool = buildTool({
  name: "CompareProfileWithRequirements",
  searchHint: "compare verified user evidence with role requirements, identify evidence gaps, and list facts that still need confirmation",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "把我的经历与目标岗位要求对照"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 把我的经历与目标岗位要求对照"
  },
  renderToolUseRejectedMessage() {
    return "把我的经历与目标岗位要求对照 rejected"
  },
  renderToolUseErrorMessage() {
    return "把我的经历与目标岗位要求对照 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 把我的经历与目标岗位要求对照"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
