// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "network-lead-verification" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    lead_candidates: z.json().describe("用户提供或从其他途径得到的联系人、内推渠道线索，必须含可公开核验的姓名、组织、链接或其他标识").optional(),
    search_result_web: z.json().describe("公开网络检索到的与线索相关的职业信息、组织信息和关联证据").optional(),
    page_content: z.json().describe("被检视的具体页面或主页内容，用于核验联系人职业身份和关系真实性").optional(),
    user_contact_rules: z.json().describe("用户对联系方式的限制和风险容忍度，以及哪些渠道被明确排除").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const NetworkLeadVerificationTool = buildTool({
  name: "NetworkLeadVerification",
  searchHint: "核验联系人或内推渠道是否真实、当前是否仍在该组织且可合法接触",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "人脉线索与内推渠道核验"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 人脉线索与内推渠道核验"
  },
  renderToolUseRejectedMessage() {
    return "人脉线索与内推渠道核验 rejected"
  },
  renderToolUseErrorMessage() {
    return "人脉线索与内推渠道核验 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 人脉线索与内推渠道核验"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
