// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "find-real-opportunities" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    opportunity_criteria: z.json().describe("用户对目标机会的要求，包括目标地区、机会类型、方向或领域、发布时间等").optional(),
    opportunity_search_results: z.json().describe("按用户条件检索到的公开岗位信息结果，用于找出候选机会").optional(),
    opportunity_detail_extracts: z.json().describe("岗位详情页原文，用于核对岗位状态、职责、组织与链接有效性").optional(),
    result_size_limit: z.number().describe("用户希望返回的岗位数量上限").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const FindRealOpportunitiesTool = buildTool({
  name: "FindRealOpportunities",
  searchHint: "寻找符合用户条件并带可核验来源的真实岗位机会",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "寻找符合我条件的真实岗位机会"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 寻找符合我条件的真实岗位机会"
  },
  renderToolUseRejectedMessage() {
    return "寻找符合我条件的真实岗位机会 rejected"
  },
  renderToolUseErrorMessage() {
    return "寻找符合我条件的真实岗位机会 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 寻找符合我条件的真实岗位机会"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
