// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "opportunity-availability-check" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    opportunities_to_check: z.json().describe("用户提供的待确认岗位清单，每项含标题、组织、链接和已知信息").optional(),
    status_page_extracts: z.json().describe("从待确认链接取得的页面原文，用于判断链接可访问性与当前发布状态").optional(),
    status_search_results: z.json().describe("针对岗位名称与组织的补充检索结果，用于交叉确认机会是否仍在招聘期").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const OpportunityAvailabilityCheckTool = buildTool({
  name: "OpportunityAvailabilityCheck",
  searchHint: "确认这些岗位机会是否仍然有效：链接能否打开、是否仍在招聘期、是否已过期或下架",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "确认这些岗位机会是否仍然有效"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return false
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 确认这些岗位机会是否仍然有效"
  },
  renderToolUseRejectedMessage() {
    return "确认这些岗位机会是否仍然有效 rejected"
  },
  renderToolUseErrorMessage() {
    return "确认这些岗位机会是否仍然有效 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 确认这些岗位机会是否仍然有效"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
