// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "rank-opportunities-to-pursue" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    verified_opportunity_list: z.json().describe("已核验的真实岗位机会清单，作为待排序的候选机会").optional(),
    user_profile: z.json().describe("用户画像中的证据、偏好与现实约束，用于判断各岗位的贴合度与优先级").optional(),
    ranking_preferences: z.json().describe("用户关心的排序因素，如地理位置、组织类型、机会类型、时间紧迫性和准备成本").optional(),
    evidence_gap_analysis: z.json().describe("已有经历与目标方向要求的对照结果，作为排序时的匹配度补充参考；没有时忽略").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const RankOpportunitiesToPursueTool = buildTool({
  name: "RankOpportunitiesToPursue",
  searchHint: "compare and rank verified job opportunities and decide where application preparation effort should go first",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "帮我排一下这些岗位先投哪些"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 帮我排一下这些岗位先投哪些"
  },
  renderToolUseRejectedMessage() {
    return "帮我排一下这些岗位先投哪些 rejected"
  },
  renderToolUseErrorMessage() {
    return "帮我排一下这些岗位先投哪些 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 帮我排一下这些岗位先投哪些"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
