// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "find-referral-entry-points" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    verified_opportunity_list: z.json().describe("用户已经确认的真实机会清单，作为寻找内推入口和人脉线索的目标对象").optional(),
    user_profile: z.json().describe("用户已有的画像信息，用于匹配与用户背景相关的公开线索和判断适用渠道").optional(),
    search_result_web: z.json().describe("公开网络检索到的机会对应公司或机构的内推、招聘、活动或联系人线索，需带来源").optional(),
    user_preferred_channels: z.json().describe("用户愿意使用的平台和渠道范围，例如官方网站、公开社区、职业社交平台等").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const FindReferralEntryPointsTool = buildTool({
  name: "FindReferralEntryPoints",
  searchHint: "find public referral entry points and public contact leads for verified opportunities with source-backed evidence",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "帮我找这些机会的公开内推入口和人脉线索"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return true
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 帮我找这些机会的公开内推入口和人脉线索"
  },
  renderToolUseRejectedMessage() {
    return "帮我找这些机会的公开内推入口和人脉线索 rejected"
  },
  renderToolUseErrorMessage() {
    return "帮我找这些机会的公开内推入口和人脉线索 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 帮我找这些机会的公开内推入口和人脉线索"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
