// Generated by scripts/generate-skill-action-tools.ts. Do not edit.
import type { ToolResultBlockParam } from '@anthropic-ai/sdk/resources/index.mjs'
import { z } from 'zod/v4'
import { buildTool, type ToolDef } from '../../Tool.js'
import {
  executeSkillAction,
  getSkillActionCommand,
} from '../../skills/skillAction.js'
import { lazySchema } from '../../utils/lazySchema.js'

const SKILL_NAME = "organization-credibility-assessment" as const

const inputSchema = lazySchema(() =>
  z.strictObject({
    organizations_to_verify: z.json().describe("用户提供的待核实组织清单，每项含组织名称、招聘上下文与相关链接").optional(),
    credibility_search_results: z.json().describe("关于组织身份、注册信息、经营动态和投诉记录的公开检索结果").optional(),
    credibility_page_extracts: z.json().describe("官网、企业信息页等原文内容，用于核对组织身份与风险信号").optional(),
  }),
)
type InputSchema = ReturnType<typeof inputSchema>

const outputSchema = lazySchema(() =>
  z.strictObject({
    skill_call_id: z.string(),
    skill_name: z.literal(SKILL_NAME),
    agent_id: z.string(),
    execution_status: z.literal('completed'),
    outcome: z.enum(['success', 'insufficient_input', 'error']),
    summary: z.string(),
    result: z.json().optional(),
    completed_at: z.string(),
    duration_ms: z.number(),
  }),
)
type OutputSchema = ReturnType<typeof outputSchema>
type Output = z.infer<OutputSchema>

export const OrganizationCredibilityAssessmentTool = buildTool({
  name: "OrganizationCredibilityAssessment",
  searchHint: "核实招聘方组织身份与可信度，检索该组织官网、企业注册信息、经营动态、投诉记录和诈骗相关报道",
  maxResultSizeChars: 100_000,
  strict: true,
  alwaysLoad: false,
  shouldDefer: true,
  async description() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  async prompt() {
    return (await getSkillActionCommand(SKILL_NAME)).description
  },
  get inputSchema(): InputSchema {
    return inputSchema()
  },
  get outputSchema(): OutputSchema {
    return outputSchema()
  },
  userFacingName() {
    return "核实招聘方组织身份与可信度"
  },
  isEnabled() {
    return true
  },
  isConcurrencySafe() {
    return false
  },
  isReadOnly() {
    return false
  },
  toAutoClassifierInput(input) {
    return JSON.stringify(input)
  },
  async checkPermissions(input) {
    return { behavior: 'allow', updatedInput: input }
  },
  renderToolUseMessage() {
    return "Run 核实招聘方组织身份与可信度"
  },
  renderToolUseRejectedMessage() {
    return "核实招聘方组织身份与可信度 rejected"
  },
  renderToolUseErrorMessage() {
    return "核实招聘方组织身份与可信度 failed"
  },
  renderToolUseProgressMessage() {
    return "Running 核实招聘方组织身份与可信度"
  },
  renderToolResultMessage(output) {
    return output.summary
  },
  async call(input, context, canUseTool) {
    const actionInput = Object.keys(input).length > 0 ? input : undefined
    return {
      data: await executeSkillAction({
        skillName: SKILL_NAME,
        actionInput,
        context,
        canUseTool,
      }),
    }
  },
  mapToolResultToToolResultBlockParam(
    content: Output,
    toolUseID: string,
  ): ToolResultBlockParam {
    return {
      type: 'tool_result',
      tool_use_id: toolUseID,
      content: JSON.stringify(content),
    }
  },
} satisfies ToolDef<InputSchema, Output>)
